---
apiVersion: v2
name: strimzi-kafka-operator
description: Strimzi Kafka Operator for Apache Kafka on Kubernetes
type: application
version: 0.1.0
appVersion: "0.49.0"
dependencies:
  - name: strimzi-kafka-operator
    version: "0.49.0"
    repository: "https://strimzi.io/charts/"


