---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
  - eventsource.yaml
  - eventbus.yaml
  - externalsecret.yaml
  - sa-rbac.yaml
  - play-workflow-sensors.yaml
  - stage-aware-resume-sensor.yaml
  - merge-to-main-sensor.yaml
  - remediation-feedback-sensor.yaml

