---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - eventsource.yaml
  - eventbus.yaml
  - externalsecret.yaml
  - sa-rbac.yaml
  - play-workflow-sensors.yaml
  - stage-aware-cleo-approval-sensor.yaml
  - stage-aware-pr-created.yaml
  - stage-aware-tess-approval-sensor.yaml
  - stage-aware-pr-merged-sensor.yaml
  - atlas-pr-monitor-sensor.yaml
  - atlas-conflict-monitor-sensor.yaml
  - atlas-batch-integration-sensor.yaml
  - merge-to-main-sensor.yaml
  - remediation-feedback-sensor.yaml

