{{- if and .Values.healer.enabled .Values.healer.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cto.healer.fullname" . }}
  namespace: {{ include "cto.namespace" . }}
  labels:
    {{- include "cto.healer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.healer.persistence.size }}
{{- end }}
