---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-webhooks-networking
  namespace: argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-webhooks-networking
  namespace: automation
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["github-eventsource-svc"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["create"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    resourceNames: ["github-webhooks"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-webhooks-networking
  namespace: automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-webhooks-networking
subjects:
  - kind: ServiceAccount
    name: github-webhooks-networking
    namespace: argocd

