---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-runner-argocd-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-runner-argocd-access
subjects:
- kind: ServiceAccount
  name: k8s-runner-gha-rs-no-permission
  namespace: arc-runners


