{{- if .Values.webhooks.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: github-webhooks
  namespace: automation
  annotations:
    argocd.argoproj.io/ignore-differences: |
      jsonPointers:
      - /status
      - /metadata/annotations
      - /metadata/managedFields
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
      namespace: automation
  hostnames:
    - "github.public.5dlabs.ai"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /github/webhook
      backendRefs:
        - group: ""
          kind: Service
          name: github-eventsource-svc
          port: 12000
          weight: 1
{{- end }}
