{{- if .Values.githubWebhooks.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: github-eventsource-svc
  namespace: automation
  labels:
    app.kubernetes.io/name: github-eventsource
spec:
  type: ClusterIP
  selector:
    eventsource-name: github
  ports:
    - name: webhook
      port: 12000
      protocol: TCP
      targetPort: 12000
{{- end }}
