---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tools.fullname" . }}-cto-config
  labels:
    {{- include "tools.labels" . | nindent 4 }}
data:
  cto-config.json: |-
{{ .Values.ctoConfig | toJson | indent 4 }}
