---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - subnet-router.yaml

# Common labels
commonLabels:
  app.kubernetes.io/part-of: headscale
  app.kubernetes.io/managed-by: argocd

