---
# Morgan PM (Project Manager) Templates ConfigMap
# Contains GitHub Projects integration scripts and helpers
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-templates-pm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cto.controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: templates
    template-type: pm
data:
{{- $files := .Files }}
{{- range $path, $_ := .Files.Glob "templates/pm/**.hbs" }}
  {{ base $path }}: |
{{ $files.Get $path | indent 4 }}
{{- end }}
