---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cto.controller.fullname" . }}-config
  labels:
    {{- include "cto.controller.labels" . | nindent 4 }}
data:
  KUBERNETES_NAMESPACE: {{ .Values.controller.config.kubernetesNamespace | quote }}
  SERVER_HOST: {{ .Values.controller.config.serverHost | quote }}
  SERVER_PORT: {{ .Values.controller.config.serverPort | quote }}
  RUST_LOG: {{ .Values.controller.config.rustLog | quote }}
