---
# Kustomization overlay for cloudflare-operator
# Deploys the upstream operator to the 'infra' namespace
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - https://github.com/adyanth/cloudflare-operator.git/config/default?ref=v0.13.1

patches:
  # Patch leader election namespace to use 'infra' instead of hardcoded 'cloudflare-operator-system'
  - target:
      kind: Deployment
      name: cloudflare-operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --leader-elect
          - --leader-election-namespace=infra
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8443
          - --metrics-secure=true
