apiVersion: v1
kind: Service
metadata:
  name: {{ include "healer.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "healer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "healer.selectorLabels" . | nindent 4 }}
---
{{- if .Values.filebrowser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "healer.fullname" . }}-filebrowser
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "healer.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebrowser
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.filebrowser.port }}
      targetPort: {{ .Values.filebrowser.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "healer.selectorLabels" . | nindent 4 }}
{{- end }}
