---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - letsencrypt-issuer.yaml
  - certificates.yaml
  - platform-ingress.yaml

# Common labels
commonLabels:
  app.kubernetes.io/part-of: platform
  app.kubernetes.io/managed-by: argocd

