{{- if .Values.buildkit.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: buildkit
  namespace: {{ .Values.global.namespace }}
  labels:
    app: buildkit
spec:
  type: NodePort
  selector:
    app: buildkit
  ports:
    - name: buildkit
      port: 1234
      targetPort: 1234
      nodePort: {{ .Values.buildkit.service.nodePort }}
      protocol: TCP
{{- end }}
